### ISSUE TITLE
Is this the implementation of "A Multi-Block-Matching Approach for Stereo"

### ISSUE THREAD

**Issue by 703962149** [midjji/openmbm#1]
Hi, midjji.
I am looking for some stereo disparity estimation algorithm that can run real-time with CPU-only. And I found "A Multi-Block-Matching Approach for Stereo" which is better than ELAS. I am trying to find whether someone implementation this algorithm and found this project. Is this the implementation of that paper? If it was, I could learn how to implementate that algorithm by this project and try to write it without cuda.

Thank you.

**Comment by midjji** [comment]
Hi,
Short answer, probably no.
This is a coursework project primarily designed to showcase the cuda
convenience lib I made. Note I have made a better one since and the one
used here is buggy...
The method itself was a disappointment, since apparently it wont work
particularly well without tricks not mentioned in the paper.  As for
recreating it, you are better off reading the paper, basically its just
blockmatching stereo with three different blocksizes combined to make the
cost.

For real time stereo the key questions are always, what hardware, at what
resolution, and how good/robust do you need it to be.
Have a look at sgm: https://core.ac.uk/download/pdf/11134866.pdf for which
there are opensource implementations available and it should be better than
elas(at least the original). Its straightforward to implement, but you will
need to go digging to find all the tricks to maximize performance. It works
in real time at 1Mpixel for an i5 with lr consistency with a decent c++
implementation using census losses.

Today I should probably also point out that deep learning based stereo is
dominating everything except for along edges where it is slightly worse.
Some of those methods can be made to run on specialized hardware in real
time. But it is also possible to run them at low res in real time on cpu.

Out of curiosity what are you doing?

**Comment by 703962149** [comment]
Thanks for your answer. 

Yesterday I had read a slides from google which metions that this algorithm needs some tricks to make it perform well. Porbably I will give up to implement it. 

The key questions of real time stereo you said help me to learn it better. Thanks.

Actually I am using deep learning based method to doing disparity estimation. However if I want to use that method with my own camera, not only with KITTI datasets,  it needs to be retrained with other dataes with different environments and their groundtruth. It may be a little difficult to get those dataes. And traditional method may work better.

I am doing my master degree project, which is a SLAM with semantic 3d reconstruction.

**Comment by midjji** [comment]
I've found that retraining a DN  trained on syth data for a new Cameras
only requires unsupervised fine-tuning in the new data.
